### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by effigies** [niflows/niflow-manager#10]
[nfm](https://pypi.org/project/nfm/) is untaken, but a question is whether we want to use that name or use something like `niflow-manager` that still provides a `nfm` CLI tool.

**Comment by kaczmarj** [comment]
I would prefer a name like `niflow-manager` for `pip`. And of course `nfm` for the CLI tool.

**Comment by effigies** [comment]
That sounds reasonable to me. So we'll change the repo name and pip package name to `niflows/niflow-manager`, and update the source directory to `niflow_manager`, but keep `nfm` as the CLI.

Will effect this change by Friday if no objections. Will do it sooner if I get more positive feedback.
