### ISSUE TITLE
Add BIDS App option to nfm init

### ISSUE THREAD

**Issue by effigies** [niflows/niflow-manager#17]
Talking to @satra, we should create a template for creating a BIDS app. For now, we'll focus on Python, in keeping with prior work.

I think it should probably be versioned, and we'll consider the paper (doi:[https://doi.org/10.1371/journal.pcbi.1005209](10.1371/journal.pcbi.1005209)) version 1.0, so my thought for syntax would be:

```Shell
nfm init --bids-app 1.0 --language python
```

cc @shotgunosine

**Comment by effigies** [comment]
`--bids-app` should default to the most recent version of BIDS Apps that are supported by `nfm`.

**Comment by effigies** [comment]
Doesn't look like we can have an option that can take the form `--bids-app` and `--bids-app 1.0` with Click.

Well, there seems to be a hack: https://stackoverflow.com/questions/40753999/python-click-make-option-value-optional

**Comment by satra** [comment]
@effigies - it may be more educational for users to have them specify the bids version, and for the code internally to support that (or not support specific versions).

**Comment by effigies** [comment]
I'm okay with that. Any preference for `--bids=<version>` vs `--bids-app=<version>`?

**Comment by satra** [comment]
my preference: `--bids <version>`
